# Working with numpy

#### To know the signature of any function: use shift + tab inside function brackets

In [3]:
import numpy as np

In [3]:
#casting numpy array using list
my_list = [1, 2, 3]
my_list = np.array(my_list)
my_list

array([1, 2, 3])

In [4]:
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_list = np.array(my_list)
my_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#np.arange() is similar to range() function. np.arange(start, end, step_size)
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#np.zeros() to generate array filled with zeros
# pass tuple for multidimensional array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# np.ones()to generate array of ones, similar to np.zeros()
print(np.ones(10))
print(np.ones((2, 3)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# np.linspace(start, end, number_of_points): use to create a 1D array of number_of_points that are evenly
# distributed between [start, end]
print(np.linspace(0,11,5))
print(np.linspace(0,11,20))

[ 0.    2.75  5.5   8.25 11.  ]
[ 0.          0.57894737  1.15789474  1.73684211  2.31578947  2.89473684
  3.47368421  4.05263158  4.63157895  5.21052632  5.78947368  6.36842105
  6.94736842  7.52631579  8.10526316  8.68421053  9.26315789  9.84210526
 10.42105263 11.        ]


In [17]:
# np.eye(n): Creating identity matrix of size n*n
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# np.random.rand(m,n) : Generating random matrix(from uniform distribution in range [0,1)) of size m*n
# NOTE: m, n are seperate arguements, not passed inside a tuple
np.random.rand(3,4)

array([[0.06227553, 0.33967345, 0.28085011, 0.79077493],
       [0.90691525, 0.86621405, 0.96004646, 0.21522843],
       [0.36179926, 0.07441459, 0.0365079 , 0.30973425]])

In [19]:
# np.random.randn(m, n): Generating random matrix(from standard normal distribution) of size m*n
# NOTE: m, n are seperate arguements, not passed inside a tuple
np.random.randn(3,4)

array([[-1.13065776,  0.54468657,  1.8180101 , -2.17700091],
       [-0.33073678,  1.27858574, -1.43218728,  0.1587197 ],
       [ 0.87593237,  2.66721651,  0.48027531,  1.79269299]])

In [20]:
# np.random.randint(start, end, n): returns array of n numbers randomly in range [start, end)
np.random.randint(0, 100, 10)

array([16, 40,  6, 34, 89, 13, 52,  7, 81, 98])

In [21]:
# np.reshape(m,n) used to reshape the given array
# Note: new shape element should be filled using the given elements in the array
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

### Numpy indexing and Selections

In [4]:
# numpy array slicing is very much similar to array slicing
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
# Array broadcasting
arr[0:5] = 99
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [7]:
array_slice = arr[0:6]
array_slice

array([99, 99, 99, 99, 99,  5])

In [8]:
array_slice[:] = 100
array_slice

array([100, 100, 100, 100, 100, 100])

In [9]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [10]:
# array_slice has a reference to arr i.e they share memory location
# numpy only creates new array from a given array when we explicitly told to do using arr.copy() method
arr_slice = arr.copy()
arr_slice

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [11]:
arr_slice[:] = 99
arr_slice

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [12]:
# Note: arr must not be changed as arr_slice and arr has different memory locations
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

### Indexing 2D matrix

In [13]:
arr = np.array([[2,3,6], [6,4,3], [3,5,8]])
arr

array([[2, 3, 6],
       [6, 4, 3],
       [3, 5, 8]])

In [14]:
# indexing using double brackets
arr[1][2]

3

In [15]:
# indexing using comma notation - mostly used
arr[1,2]

3

In [16]:
# Slicing the matrix
arr[:2, 1:]

array([[3, 6],
       [4, 3]])

In [17]:
# Conditional selection in np.array()
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [19]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [20]:
# Or we can do directly
arr[arr > 5]  # commonly used

array([ 6,  7,  8,  9, 10])

### Numpy Operations

In [21]:
import numpy as np

# Array with array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [25]:
arr / arr
# NOTE: for the first element we are doing 0/0, it should give an exception in normal code
# But in case of numpy array it gives a runtime warning so that rest of the code can able to be executed

C:\Users\AYUSHS~1\AppData\Local\Temp/ipykernel_9344/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
# Array with scaler (works with bradcasting of scaler)
1 / arr

C:\Users\AYUSHS~1\AppData\Local\Temp/ipykernel_9344/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [27]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [29]:
# Universal array functions - visit https://numpy.org/doc/stable/reference/ufuncs.html#broadcasting 
# some common universal functions are np.sqrt(), np.max(), np.min(), np.exp() etc